version: '3'
services:
    keycloak:
        image: 'quay.io/keycloak/keycloak:15.0.2'
        container_name: keycloak-quoteapp1
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            - KEYCLOAK_IMPORT=/tmp/test-realm.json
            - DB_VENDOR=h2 # don't try to discover mysql in the network
        volumes:
            - ../server/src/main/resources/keycloak/realm-export.json:/tmp/test-realm.json
        ports:
            - 8082:8080
            - 9990:9990


#run using
#docker-compose -f docker-compose.yml up
# or just docker-compose up
